Buzzvil/buzz-sdk-samples

- buzzad-benefit-web/web/ids.js
- buzzad-benefit-web/web/index.html
- buzzad-benefit-web/web/index.js
Benefit JS 샘플 웹페이지에서 JS SDK 1.2.0을 사용하도록 하고, 코드를 약간 정리하였습니다.
* Benefit JS SDK를 1.0.4에서 1.2.0을 사용하도록 변경
* 코드 가독성을 위해 광고를 1개만 요청하게 하고, 광고 큐를 없앰
* NO_FILL 등의 사유로 보여줄 광고가 없는 경우 광고 영역을 보이지 않게 함
> Benefit JS 샘플 웹페이지에서 JS SDK 1.2.0 사용. 코드 정리

- buzzad-benefit-web/android/app/build.gradle
- buzzad-benefit-web/android/app/src/main/AndroidManifest.xml
- buzzad-benefit-web/android/app/src/main/java/com/buzzvil/benefit/web/App.java
- buzzad-benefit-web/android/app/src/main/java/com/buzzvil/benefit/web/MainActivity.java
- buzzad-benefit-web/android/build.gradle
Benefit JS용 안드로이드 샘플앱에서 Benefit 안드로이드 SDK 2.0.2 버전을 사용하도록 변경하였습니다.
* 연동 버전을 1.7.0에서 2.0.2로 변경
* APP_KEY를 AndroidManifest로 옮김
* compileOptions에 VERSION_1_8 추가 (없으면 빌드 안됨)
* SessionReadyBroadcastReceiver 사용할 때 불필요한 분기 처리 제거 (API 내부에서 같은 분기처리를 하고 있어서, 해당 분기처리가 없어도 세션이 있는 경우 바로 콜백이 실행됨)
> Benefit JS 안드로이드 샘플앱에서 benefit Android SDK 2.0.2를 사용

- buzzad-benefit-web/web/index.html
- buzzad-benefit-web/web/index.js
연동 가이드를 업데이트하면서 변경된 수정사항을 샘플 코드에도 반영하였습니다.
1. 기존의 의미를 파악하기 어려웠던 'rootView'라는 변수명을 'placementView'로 변경하여, 해당 지면에 대한 view임을 파악할 수 있도록 하였습니다.
2. 광고 지면의 id를 'nativeAd' 대신에 'placement1'로 변경하여, 광고 지면이라는 느낌을 주면서 한 페이지에 여러개가 있어도 됨을 암시하고자 하였습니다.
> [Benefit-JS] 변경된 가이드에 따라 코드 변경

- buzzad-benefit-web/web/index.js
퍼블리셔가 구현한 callback에서 에러가 발생했을 때 아래의 catch문에서 그 에러가 잡혀서 마치 SDK에서 에러가 생긴 것처럼 보이는 문제를 수정하였습니다.
> 퍼블리셔의 코드에서 생긴 에러가 SDK에서 생긴 것처럼 보이지 않도록 코드 수정

- buzz-pedometer/app/build.gradle
- buzz-pedometer/app/src/main/java/com/buzzvil/pedometer/sample/MainActivity.java
Pedometer sdk의 버전을 1.1.2 로 명시적으로 버전을 올렸습니다. 
그리고 redeemable milestone이 없는 상황에서 Request reward 버튼이 enable되는 UI버그가 있어 수정했습니다.
> bump up pedometer sdk version to 1.1.2

- buzz-pedometer/README.md
- buzz-pedometer/app/build.gradle
- buzz-pedometer/app/src/main/java/com/buzzvil/pedometer/sample/MainActivity.java
Android Q 이상에서 Activity recognition permission을 받도록 수정하였고, 
STEP_COUNTER 센서를 지원하지 않는 디바이스에서는 activate시 토스트가 뜨도록 변경되었습니다.
> update buzz-pedometer-sdk to 1.2.5

- buzzad-benefit-pop/app/src/pedometerpop/AndroidManifest.xml
- buzzad-benefit-pop/app/src/pedometerpop/java/com/buzzvil/buzzad/benefit/popsample/java/App.java
popsample 에서 AppId를 변수로 선언하여 사용하고 있었습니다. 
AppId를 manifest로 옮겼고, BuzzAdPopPedometer 에서는 manifest 에서 직접 참조하여 사용할 것 입니다.
SDK 배포 후 머지하겠습니다.
> [PO-1203][FIX] Use AppId in manifest

- buzzad-benefit-push/app/src/main/java/com/buzzvil/buzzad/benefit/notiplussample/App.java
- buzzad-benefit-push/app/src/main/java/com/buzzvil/buzzad/benefit/notiplussample/CustomNotificationWorker.java
- buzzad-benefit-push/app/src/main/java/com/buzzvil/buzzad/benefit/notiplussample/MainActivity.java
- buzzad-benefit-push/app/src/main/java/com/buzzvil/buzzad/benefit/notiplussample/RestartReceiver.java
내부적으로 feed unit id를 이용하여 feed config를 조회하고 사용하고 있어서 put extra 부분이 필요없어졌습니다.
그리고 유닛아이디 이름이 노티플러스로 헷갈리는 것 같아서 UNIT_ID_FEED로 리네임했습니다.
> Fix push compile

- buzzad-benefit-ios/BABSample/AppDelegate.m
- buzzad-benefit-ios/BABSample/CarouselView.m
- buzzad-benefit-ios/BABSample/WebViewController.m
- buzzad-benefit-ios/Podfile
- buzzad-benefit-ios/Podfile.lock
iOS 퍼블릭 샘플의 버전을 2.2.5로 업데이트 합니다.
> [OUT-301][MINOR] Bump iOS BuzzAdBenefit SDK to 2.2.5

- buzzad-benefit-ios/Podfile
- buzzad-benefit-ios/Podfile.lock
- buzzad-benefit-ios/README.md
- iOS SDK 버전을 업데이트 했습니다.
- iOS 릴리즈 노트에 최신 버전 정보를 추가하고 Android 릴리즈 노트와 비슷한 포맷을 가지도록 변경했습니다.
> [MINOR] Bump iOS BuzzAdBenefit SDK to 2.4.2

- buzzad-benefit-ios/BABSample/Feed/CustomFeedAdViewHolder.m
- buzzad-benefit-ios/BABSample/Feed/CustomFeedCpsAdViewHolder.m
- buzzad-benefit-ios/BABSample/Native/NativeViewController.m
샘플 코드를 잘못 작성한 부분을 수정했습니다. 광고를 렌더링 할 때 마다 `ViewBinder`를 매번 생성하는 코드를 `ViewBinder`를 한번만 생성하고 재사용하게 끔 변경했습니다.
> BuzzAd iOS SDK 샘플 코드 오류 수정

- buzzad-benefit-ios/Podfile
- buzzad-benefit-ios/Podfile.lock
- buzzad-benefit-ios/README.md
퍼블릭 샘플 애플리케이션의 BuzzAd iOS SDK 버전을 3.5.1 으로 업데이트 했습니다.
> BuzzAd iOS SDK 3.5.1

- buzzscreen-extension/COMMUNICATION-UTILS.md
변경사항
1. `extension-client`, `extension-host`를 `buzzscreen-host`, `buzzscreen-client`으로 수정합니다.
2. 명확성을 위해 Extension SDK -> BuzzScreen Extension SDK 으로 변경했습니다.
> [OUTPUT-351] Fix typo (BS Ext SDK communication utils)

- buzzad-benefit-ios/Podfile
- buzzad-benefit-ios/Podfile.lock
- buzzad-benefit-ios/README.md
퍼블릭 샘플 애플리케이션의 BuzzAd iOS SDK 버전을 3.13.1 으로 업데이트 했습니다.
> BuzzAd iOS SDK 3.11.3

- buzzad-benefit-web/web/index.html
BuzzAd JS SDK에 Sentry를 끄는 옵션을 추가하여 새 버전인 1.3.1으로 배포하였습니다. 이에 따라 샘플 코드에서도 새 버전을 사용하도록 하였습니다.
원래는 1.3.0으로 배포할 계획이었으나, Sentry에 문제가 있어서 항상 끄는 걸로 기본값을 변경하면서 1.3.1로 새로 배포하였습니다.
> [OUT-1645] BuzzAd JS SDK 1.3.1으로 업데이트

- buzzad-benefit-ios/BABSample/AppDelegate.m
- buzzad-benefit-ios/Podfile
- buzzad-benefit-ios/Podfile.lock
- buzzad-benefit-ios/README.md
퍼블릭 샘플 애플리케이션의 BuzzAd iOS SDK 버전을 3.21.2 으로 업데이트 합니다.
> BuzzAd iOS SDK 3.21.2

- buzzad-benefit-ios/Podfile
- buzzad-benefit-ios/Podfile.lock
- buzzad-benefit-ios/README.md
퍼블릭 샘플 애플리케이션의 BuzzAd iOS SDK 버전을 3.23.3 으로 업데이트 합니다.
> BuzzAd iOS SDK 3.23.3

- buzzad-benefit-ios/Podfile
- buzzad-benefit-ios/Podfile.lock
- buzzad-benefit-ios/README.md
퍼블릭 샘플 애플리케이션의 BuzzAd iOS SDK 버전을 3.25.0 으로 업데이트 합니다.
> BuzzAd iOS SDK 3.25.0

- buzzad-benefit-ios/Podfile
- buzzad-benefit-ios/Podfile.lock
퍼블릭 샘플 애플리케이션의 BuzzAd iOS SDK 버전을 3.29.1 으로 업데이트 합니다.
> BuzzAd iOS SDK 3.29.1

- buzzad-benefit-ios/Podfile
- buzzad-benefit-ios/Podfile.lock
- buzzad-benefit-ios/README.md
퍼블릭 샘플 애플리케이션의 BuzzAd iOS SDK 버전을 3.35.5 으로 업데이트 합니다.
> BuzzAd iOS SDK 3.35.5

- buzzad-benefit-ios/Podfile
- buzzad-benefit-ios/Podfile.lock
- buzzad-benefit-ios/README.md
퍼블릭 샘플 애플리케이션의 BuzzAd iOS SDK 버전을 3.37.1 으로 업데이트 합니다.
> BuzzAd iOS SDK 3.37.1

- buzzad-benefit-ios/Podfile
- buzzad-benefit-ios/Podfile.lock
- buzzad-benefit-ios/README.md
퍼블릭 샘플 애플리케이션의 BuzzAd iOS SDK 버전을 3.39.1 으로 업데이트 합니다.
> BuzzAd iOS SDK 3.39.1

- buzzad-benefit-ios/Podfile
- buzzad-benefit-ios/Podfile.lock
- buzzad-benefit-ios/README.md
퍼블릭 샘플 애플리케이션의 BuzzAd iOS SDK 버전을 3.41.0 으로 업데이트 합니다.
> BuzzAd iOS SDK 3.41.0

- README.md
- buzzad-benefit-ios/README.md
- buzzad-benefit/README.md
- buzzbooster-android/README.md
- buzzbooster-flutter/README.md
- buzzbooster-ios/README.md
- buzzbooster-react-native/README.md
- buzzscreen/README.md
- buzzscreen/README_EN.md
- buzzvil-sdk-ios/README.md
- buzzvil-sdk/README.md
라이센스 정보를 제공하는 부분의 링크가 깨져있어서 수정했습니다.
- 원본 파일: 상대경로가 깨져있어서 절대경로로 변경했습니다.
- 랜더링 버전: 다른 리포지토리 파일이 링크 걸려있어서 수정했습니다.
> [OUTPUT-2964] Fix path for 3rd party licenses

- buzzvil-sdk-ios/Podfile
- buzzvil-sdk-ios/Podfile.lock
- buzzvil-sdk-ios/README.md
- buzzvil-sdk-ios/buzzvil-sdk-ios-objc/AppDelegate.m
- buzzvil-sdk-ios/buzzvil-sdk-ios-swift/AppDelegate.swift
reviewer : @Gongcu 
BuzzBenefit SDK 버전을 5.3.0 으로 올립니다.
새롭게 추가된 BuzzBenefitUser.marketingStatus 관련 코드가 추가되었습니다.
BuzzBenefit 5.3.0 public 배포 이후에 pod install 이 필요합니다.
> BuzzvilSDK iOS 5.3.0

- buzzvil-sdk-android/app/src/main/java/com/buzzvil/sample/buzzvilsdksample/nativead/NativeCarouselActivity.kt
addItemDecoration을 한 번만 하도록 위치를 옮깁니다.
https://github.com/Buzzvil/buzz-android/pull/3581 와 동일한 작업입니다.
> [OUTPUT-3029] 샘플앱에서 Load Carousel을 여러 번 하면 아이템 크기가 계속 작아지는 문제 해결

- buzzvil-sdk-ios/buzzvil-sdk-ios-swift/Native/Carousel/CarouselViewController.swift
iOS Native 2.0 무한루프 구현 시 샘플코드 누락으로 이를 보충합니다.
> [OUTPUT-3772] buzzvil SDK iOS 에서 무한루프 구현 시 샘플 코드가 누락되어 추가합니다.

- buzzvil-sdk-ios/buzzvil-sdk-ios-swift/ViewController.swift
메인화면의  Banner 버튼의 레이아웃이 잘못 구현되어 있어서 위치를 의도한곳으로 옮깁니다.
> [FIX] BuzzvilSDK iOS 메인화면의 Banner Layout 을 수정합니다.
