buzzad-benefit-web/android/app/src/main/java/com/buzzvil/benefit/web/MainActivity.java
buzzad-benefit-web/web/index.html
buzzad-benefit-web/web/index.js

네이티브 SDK와 웹 SDK의 프로필 싱크를 테스트할 수 있도록 안드로이드 샘플앱과 웹페이지를 업데이트하였습니다.
[IN-100](https://buzzvil.atlassian.net/browse/IN-100)카드의 댓글에 있는 영상에서 모습을 확인하실 수 있습니다.

[IN-100] 네이티브-웹 프로필 싱크 샘플앱

---

buzzad-benefit-pop/PopBenefit1SamplePublisher/app/build.gradle
buzzad-benefit-pop/PopBenefit1SamplePublisher/app/src/main/java/com/buzzvil/buzzad/benefit/popbenefit1samplepublisher/App.java

Benefit 1.x 를 사용하는 PopSample 에 benefit-pop:1.7.+ 을 적용. (hotfix 는 바로 적용되게 하기 위함)

[PopBenefit1SamplePublisher] Apply Benefit1.7.3

---

buzz-pedometer/README.md
buzz-pedometer/app/build.gradle

readme.md 파일 추가했습니다.
그리고, 샘플앱의 버전을 SDK버전과 동일하게 변경했습니다.

Add readme.md for pedometer and fix app version

---

buzzad-benefit/app/src/main/java/com/buzzvil/buzzad/benefit/sample/publisher/MainActivity.java
buzzad-benefit/app/src/main/java/com/buzzvil/buzzad/benefit/sample/publisher/feed/CustomFeedToolbarHolder.java
buzzad-benefit/app/src/main/res/layout/activity_main.xml
buzzad-benefit/build.gradle

BuzzAdBenefit 2.5.+ 버전 연동 및 Feed Tab UI 버튼을 추가하였습니다.

update BuzzAdBenefit version to 2.5.+

---

buzzad-benefit-pop/app/src/main/java/com/buzzvil/buzzad/benefit/popsample/java/custom/CustomPopHeaderViewAdapter.java
buzzad-benefit-pop/app/src/main/res/layout/view_custom_preview_message.xml

CustomPreviewMessage 이름 변경에 따른 코드 수정

[CD-833] Update customPreviewMessage name

---

buzzad-benefit-pop/build.gradle
buzzad-benefit-unity/build.gradle
buzzad-benefit/README.md
buzzad-benefit/build.gradle
buzzscreen/README.md
buzzscreen/build.gradle

buzzad-benefit-notification 은 일단 제외합니다

apply buzzad-sdk 2.9.0 and buzzscreen 3.13.0

---

buzzad-benefit-pop/app/src/pedometerpop/java/com/buzzvil/buzzad/benefit/popsample/java/App.java

unit 이 모두 더미로 설정되어 있어서 새로 생성하여 추가했습니다.
100 걸음 걸어서 미션 완료까지 확인했습니다.

[PO-1182][FIX] 유닛을 추가하여 업데이트

---

buzzad-benefit-push/app/build.gradle
buzzad-benefit-push/build.gradle

https://buzzvil.slack.com/archives/C01J573LRG9/p1618386672053400?thread_ts=1618308235.023100&cid=C01J573LRG9
클라우드 스미스로 이전하고 위 쓰레드에서 나온 이슈를 수정합니다.

[PO-1042] Migrate to cloudsmith, and fix err

---

buzz-pedometer/build.gradle
buzzad-benefit-extpoint/build.gradle
buzzad-benefit-pop/PopBenefit1SamplePublisher/build.gradle
buzzad-benefit-pop/build.gradle
buzzad-benefit-unity/buzzad-app-module/build.gradle
buzzad-benefit-web/android/build.gradle
buzzad-benefit-web/flutter/android/app/build.gradle
buzzad-benefit-web/flutter/android/build.gradle
buzzad-benefit/build.gradle
buzzad-offerwall/buzzad-sample/build.gradle
buzzscreen-extension-migration/build.gradle
buzzscreen/sample/build.gradle

replace url to cloudsmith

---

buzzscreen/build.gradle

Apply buzzscreen 4.0.0

---

buzzad-benefit/app/build.gradle
buzzad-benefit/app/src/main/AndroidManifest.xml
buzzad-benefit/app/src/main/java/com/buzzvil/buzzad/benefit/sample/publisher/MainActivity.java
buzzad-benefit/app/src/main/java/com/buzzvil/buzzad/benefit/sample/publisher/carousel/CarouselAdapter.kt
buzzad-benefit/app/src/main/java/com/buzzvil/buzzad/benefit/sample/publisher/carousel/CarouselItem.kt
buzzad-benefit/app/src/main/java/com/buzzvil/buzzad/benefit/sample/publisher/carousel/NativeCarouselActivity.kt
buzzad-benefit/app/src/main/java/com/buzzvil/buzzad/benefit/sample/publisher/carousel/PaddingDividerDecoration.kt
buzzad-benefit/app/src/main/res/drawable/ic_chevron_right.xml
buzzad-benefit/app/src/main/res/layout/activity_main.xml
buzzad-benefit/app/src/main/res/layout/activity_native_carousel.xml
buzzad-benefit/app/src/main/res/layout/view_item_carousel.xml
buzzad-benefit/app/src/main/res/values/styles.xml
buzzad-benefit/build.gradle

[OUT-1205] 캐러셀 UI 연동 샘플 코드 작성

---

buzzbooster-ios/Podfile
buzzbooster-ios/README.md

- BuzzBooster version을 patch에서 최신으로 유지하게 변경했습니다.

[MINOR] BuzzBooster version을 최신으로 유지하게 변경했습니다.

---

buzzad-benefit-ios/BABSample.xcodeproj/project.pbxproj
buzzad-benefit-ios/BABSample/AppDelegate.m
buzzad-benefit-ios/BABSample/Feed/CustomFeedBaseRewardViewHolder.h
buzzad-benefit-ios/BABSample/Feed/CustomFeedBaseRewardViewHolder.m
buzzad-benefit-ios/Podfile
buzzad-benefit-ios/Podfile.lock
buzzad-benefit-ios/README.md

퍼블릭 샘플 애플리케이션의 BuzzAd iOS SDK 버전을 3.2.1 으로 업데이트 했습니다.

BuzzAd iOS SDK 3.2.1

---

buzzad-benefit-ios/BABSample/Feed/CustomFeedAdViewHolder.m
buzzad-benefit-ios/BABSample/Feed/CustomFeedCpsAdViewHolder.m
buzzad-benefit-ios/BABSample/Interstitial/InterstitialViewController.m
buzzad-benefit-ios/BABSample/Native/CustomCtaView.m
buzzad-benefit-ios/BABSample/Native/NativeViewController.m
buzzad-benefit-ios/Podfile
buzzad-benefit-ios/Podfile.lock
buzzad-benefit-ios/README.md

퍼블릭 샘플 애플리케이션의 BuzzAd iOS SDK 버전을 3.3.0 으로 업데이트 했습니다.

BuzzAd iOS SDK 3.3.0

---

buzzad-benefit-extpoint/build.gradle
buzzad-benefit-pop/build.gradle
buzzad-benefit-push/build.gradle
buzzad-benefit-web/android/build.gradle
buzzad-benefit/README.md
buzzad-benefit/build.gradle
buzzscreen-extension-migration/build.gradle
buzzscreen/README.md
buzzscreen/build.gradle

R220624; buzzad-3.13.0; buzzscreen-4.7.0;

---

buzzad-benefit-extpoint/build.gradle
buzzad-benefit-pop/build.gradle
buzzad-benefit-push/build.gradle
buzzad-benefit-web/android/build.gradle
buzzad-benefit/README.md
buzzad-benefit/build.gradle
buzzscreen-extension-migration/build.gradle
buzzscreen/README.md
buzzscreen/build.gradle

R220722; buzzad-3.15.0; buzzscreen-4.9.0;

---

buzzad-benefit-extpoint/build.gradle
buzzad-benefit-pop/build.gradle
buzzad-benefit-push/build.gradle
buzzad-benefit-web/android/build.gradle
buzzad-benefit/README.md
buzzad-benefit/build.gradle
buzzscreen-extension-migration/build.gradle
buzzscreen/README.md
buzzscreen/build.gradle

R220819; buzzad-3.17.0; buzzscreen-4.11.0;

---

buzzad-benefit-extpoint/build.gradle
buzzad-benefit-pop/build.gradle
buzzad-benefit-push/build.gradle
buzzad-benefit-web/android/build.gradle
buzzad-benefit/README.md
buzzad-benefit/build.gradle
buzzscreen-extension-migration/build.gradle
buzzscreen/README.md
buzzscreen/build.gradle

R221014; buzzad-3.21.0; buzzscreen-4.15.0;

---

buzzbooster-flutter/README.md

Flutter 디렉토리에 RN으로 명시한 typo 해결 Update README.md

---

buzzad-benefit-extpoint/build.gradle
buzzad-benefit-pop/build.gradle
buzzad-benefit-push/build.gradle
buzzad-benefit-web/android/build.gradle
buzzad-benefit/README.md
buzzad-benefit/build.gradle
buzzscreen-extension-migration/build.gradle
buzzscreen/README.md
buzzscreen/build.gradle

R221111; buzzad-3.23.0; buzzscreen-4.17.0;

---

buzzad-benefit-extpoint/build.gradle
buzzad-benefit-pop/build.gradle
buzzad-benefit-push/build.gradle
buzzad-benefit-web/android/build.gradle
buzzad-benefit/README.md
buzzad-benefit/build.gradle
buzzscreen-extension-migration/build.gradle
buzzscreen/README.md
buzzscreen/build.gradle

R221209; buzzad-3.25.0; buzzscreen-4.19.0;

---

buzzad-benefit-extpoint/build.gradle
buzzad-benefit-pop/build.gradle
buzzad-benefit-push/build.gradle
buzzad-benefit-web/android/build.gradle
buzzad-benefit/README.md
buzzad-benefit/app/src/main/java/com/buzzvil/buzzad/benefit/sample/publisher/App.java
buzzad-benefit/app/src/main/res/drawable/custom_tab_indicator_seletor.xml
buzzad-benefit/app/src/main/res/values/colors.xml
buzzad-benefit/build.gradle
buzzscreen-extension-migration/build.gradle
buzzscreen/README.md
buzzscreen/build.gradle

퍼블릭 샘플 애플리케이션의 BuzzAd Android SDK 버전을 3.27.0 / BuzzScreen 4.21.0 으로 업데이트 합니다.

R230106; buzzad-3.27.0; buzzscreen-4.21.0; 

---

buzzbooster-flutter/ios/Podfile
buzzbooster-flutter/ios/Podfile.lock
buzzbooster-flutter/lib/main.dart
buzzbooster-flutter/pubspec.lock
buzzbooster-flutter/pubspec.yaml

아래와 같은게 있었는데 CampaignType 이동을 다시 추가했기 때문에 제거합니다
그 외에는 코멘트 확인 부탁드림다

BuzzBooster Flutter 2.0.x

---

buzzbooster-android/README.md
buzzbooster-flutter/README.md
buzzbooster-flutter/android/app/src/main/AndroidManifest.xml
buzzbooster-flutter/android/app/src/main/res/values/styles.xml
buzzbooster-flutter/ios/Podfile
buzzbooster-flutter/ios/Podfile.lock
buzzbooster-flutter/lib/main.dart
buzzbooster-flutter/pubspec.lock
buzzbooster-flutter/pubspec.yaml
buzzbooster-ios/README.md
buzzbooster-react-native/App.js
buzzbooster-react-native/Page/EventView.js
buzzbooster-react-native/Page/HomePage.js
buzzbooster-react-native/Page/LinkPage.js
buzzbooster-react-native/Page/OptInMarketingPage.js
buzzbooster-react-native/README.md
buzzbooster-react-native/ios/Podfile
buzzbooster-react-native/ios/Podfile.lock
buzzbooster-react-native/package-lock.json
buzzbooster-react-native/package.json

- BuzzBooster README.md update
- FL 2.0.x 연동
- RN 2.0.x 연동

BuzzBooster RN, FL 2.0.x

---

buzzad-benefit-extpoint/build.gradle
buzzad-benefit-pop/build.gradle
buzzad-benefit-push/build.gradle
buzzad-benefit-web/android/build.gradle
buzzad-benefit/README.md
buzzad-benefit/build.gradle
buzzscreen-extension-migration/build.gradle
buzzscreen/README.md
buzzscreen/build.gradle

R230203; buzzad-3.29.0; buzzscreen-4.23.0;

---

buzzbooster-ios/BSTSample.xcodeproj/project.pbxproj
buzzbooster-ios/BSTSample/AppDelegate.swift
buzzbooster-ios/BSTSample/OptInMarketingViewController.swift
buzzbooster-ios/BSTSample/ViewController.swift
buzzbooster-ios/Podfile
buzzbooster-ios/Podfile.lock
buzzbooster-ios/README.md

@huspark @dkghazz 
- REAMDME.md 수정
- 마케팅 수신 동의 유도 캠페인 연동 추가
- 스탬프 캠페인 액션 추가

[MINOR] BuzzBooste iOS 샘플앱 개선

---

buzzbooster-android/app/build.gradle
buzzbooster-android/app/src/main/java/com/buzzvil/booster/sample/publisher/App.kt
buzzbooster-flutter/lib/main.dart
buzzbooster-flutter/pubspec.lock
buzzbooster-flutter/pubspec.yaml
buzzbooster-ios/BSTSample/AppDelegate.swift
buzzbooster-ios/Podfile
buzzbooster-ios/Podfile.lock
buzzbooster-react-native/App.js
buzzbooster-react-native/package-lock.json
buzzbooster-react-native/package.json

@dkghazz 
2.2.0으로 업데이트하고 새로 추가된 EventListener를 연동했습니다.

BuzzBooster SDK 2.2.0 Update

---

buzzad-benefit/app/src/main/java/com/buzzvil/buzzad/benefit/sample/publisher/MainActivity.java
buzzad-benefit/app/src/main/res/layout/activity_main.xml

(연동 QA) 퍼블릭 샘플앱에 개인정보 수집동의 관련 코드를 추가합니다.
https://github.com/Buzzvil/buzz-sdk-samples/assets/45025283/3a7a8c36-04ce-478c-bda0-9b58df15ea3a
@JuHyang `BuzzAdBenefit.getPrivacyPolicyManager()`가 nullable인데 null 체크를 안하려니까 찜찜합니다. null 체크를 하는게 좋을까요? 예제니까 심플하게 가는게 좋을까요?

[OUTPUT-1830] Add privacy policy example

---

buzzad-benefit-extpoint/build.gradle
buzzad-benefit-pop/build.gradle
buzzad-benefit-push/build.gradle
buzzad-benefit-web/android/build.gradle
buzzad-benefit/README.md
buzzad-benefit/build.gradle
buzzscreen-extension-migration/build.gradle
buzzscreen/README.md
buzzscreen/build.gradle

R230526; buzzad-3.37.0; buzzscreen-4.31.0;

---

buzzbooster-android/CHANGELOG.md
buzzbooster-android/app/build.gradle
buzzbooster-android/app/src/main/java/com/buzzvil/booster/sample/publisher/MainActivity.kt
buzzbooster-android/app/src/main/res/layout/activity_main.xml
buzzbooster-flutter/CHANGELOG.md
buzzbooster-flutter/ios/Podfile.lock
buzzbooster-flutter/lib/main.dart
buzzbooster-flutter/pubspec.lock
buzzbooster-flutter/pubspec.yaml
buzzbooster-ios/BSTSample/AppDelegate.swift
buzzbooster-ios/BSTSample/CustomEntryPointButton.swift
buzzbooster-ios/BSTSample/OptInMarketingViewController.swift
buzzbooster-ios/BSTSample/ViewController.swift
buzzbooster-ios/CHANGELOG.md
buzzbooster-ios/Podfile
buzzbooster-ios/Podfile.lock
buzzbooster-react-native/CHANGELOG.md
buzzbooster-react-native/Page/HomePage.js
buzzbooster-react-native/ios/Podfile.lock
buzzbooster-react-native/package-lock.json
buzzbooster-react-native/package.json

Update BuzzBooster 3.0.x 

---

buzzad-benefit-extpoint/build.gradle
buzzad-benefit-pop/build.gradle
buzzad-benefit-push/build.gradle
buzzad-benefit-web/android/build.gradle
buzzad-benefit/README.md
buzzad-benefit/build.gradle
buzzscreen-extension-migration/build.gradle
buzzscreen/README.md
buzzscreen/build.gradle

R230623; buzzad-3.39.0; buzzscreen-4.33.0;

---

buzzbooster-android/CHANGELOG.md
buzzbooster-android/app/build.gradle
buzzbooster-flutter/CHANGELOG.md
buzzbooster-flutter/ios/Podfile
buzzbooster-flutter/ios/Podfile.lock
buzzbooster-flutter/pubspec.lock
buzzbooster-flutter/pubspec.yaml
buzzbooster-ios/CHANGELOG.md
buzzbooster-ios/Podfile
buzzbooster-ios/Podfile.lock
buzzbooster-react-native/CHANGELOG.md
buzzbooster-react-native/ios/Podfile
buzzbooster-react-native/ios/Podfile.lock
buzzbooster-react-native/package-lock.json
buzzbooster-react-native/package.json

@dkghazz 
Podfile에 추가된 아래 코드는 Xcode 14.3을 대응하기 위함입니다
```
installer.pods_project.targets.each do |target|
target.build_configurations.each do |config|
config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
end
```

BuzzBooster 3.1.0 Sample App, ChangeLog 업데이트

---

buzzad-benefit-extpoint/build.gradle
buzzad-benefit-pop/build.gradle
buzzad-benefit-push/build.gradle
buzzad-benefit-web/android/build.gradle
buzzad-benefit/README.md
buzzscreen-extension-migration/build.gradle
buzzscreen/README.md
buzzscreen/build.gradle

R230721; buzzad-3.41.0; buzzscreen-4.35.0;

---

buzzad-benefit-extpoint/build.gradle
buzzad-benefit-pop/build.gradle
buzzad-benefit-push/build.gradle
buzzad-benefit-web/android/build.gradle
buzzad-benefit/README.md
buzzscreen-extension-migration/build.gradle
buzzscreen/README.md
buzzscreen/build.gradle

R230818; 
buzzad-benefit-3.43; 
buzzscreen-4.37;

R230818; buzzad-benefit-3.43; buzzscreen-4.37;

---

buzzad-benefit-extpoint/build.gradle
buzzad-benefit-pop/build.gradle
buzzad-benefit-push/build.gradle
buzzad-benefit-web/android/build.gradle
buzzad-benefit/README.md
buzzscreen-extension-migration/build.gradle
buzzscreen/README.md
buzzscreen/build.gradle

버전업과 릴리즈노트인 README.md 를 수정했습니다. 
- R230915;
- buzzad-benefit-3.45; 
- buzzscreen-4.39;

R230915; buzzad-benefit-3.45; buzzscreen-4.39;

---

buzzvil-sdk-android/app/src/main/AndroidManifest.xml
buzzvil-sdk-android/app/src/main/java/com/buzzvil/sample/buzzvilsdksample/App.kt
buzzvil-sdk-android/app/src/main/java/com/buzzvil/sample/buzzvilsdksample/Constant.kt
buzzvil-sdk-android/app/src/main/java/com/buzzvil/sample/buzzvilsdksample/MainActivity.kt
buzzvil-sdk-android/app/src/main/java/com/buzzvil/sample/buzzvilsdksample/custom/CustomBrowserActivity.kt
buzzvil-sdk-android/app/src/main/java/com/buzzvil/sample/buzzvilsdksample/custom/CustomFeedHeaderViewAdapter.kt
buzzvil-sdk-android/app/src/main/java/com/buzzvil/sample/buzzvilsdksample/custom/CustomLauncher.kt
buzzvil-sdk-android/app/src/main/java/com/buzzvil/sample/buzzvilsdksample/pop/CustomPopAdMessageView.kt
buzzvil-sdk-android/app/src/main/java/com/buzzvil/sample/buzzvilsdksample/pop/CustomPopToolbarHolder.kt
buzzvil-sdk-android/app/src/main/java/com/buzzvil/sample/buzzvilsdksample/pop/CustomPopUtilityLayoutHandler.kt
buzzvil-sdk-android/app/src/main/java/com/buzzvil/sample/buzzvilsdksample/pop/YourPopControlService.kt
buzzvil-sdk-android/app/src/main/res/layout/activity_custom_browser.xml
buzzvil-sdk-android/app/src/main/res/layout/activity_main.xml
buzzvil-sdk-android/app/src/main/res/layout/feed_header_layout.xml
buzzvil-sdk-android/app/src/main/res/layout/notification_pop.xml
buzzvil-sdk-android/app/src/main/res/layout/your_pop_ad_message_view.xml
buzzvil-sdk-android/app/src/main/res/layout/your_pop_utility_view.xml

Buzzvil SDK 샘플앱에 있는 코드를 Kotlin 으로 제공합니다.
Interstitial
Pop 이 추가되었습니다.

[OUTPUT-2914] Provide Kotlin Code in Buzzvil Sample App

---

buzzad-benefit-extpoint/build.gradle
buzzad-benefit-pop/build.gradle
buzzad-benefit-push/build.gradle
buzzad-benefit-web/android/build.gradle
buzzad-benefit/README.md
buzzad-benefit/build.gradle
buzzscreen-extension-migration/build.gradle
buzzscreen/README.md
buzzscreen/build.gradle
buzzvil-sdk-android/app/build.gradle
buzzvil-sdk/README.md

R231110 스프린트 버전 적용
BuzzBenefit
- buzzvil-bom-5.1; 
BuzzAd, Buzzscreen
- buzzad-benefit-3.49; 
- buzzscreen-4.43;

R231110; buzzvil-bom-5.1; buzzad-benefit-3.49; buzzscreen-4.43;

---

buzzvil-sdk-ios/Podfile
buzzvil-sdk-ios/Podfile.lock
buzzvil-sdk-ios/README.md

BuzzvilSDK iOS 5.1.0

---

buzzvil-sdk-ios/Podfile
buzzvil-sdk-ios/Podfile.lock
buzzvil-sdk-ios/README.md

BuzzvilSDK iOS 5.1.1

---

buzzbooster-android/app/src/main/java/com/buzzvil/booster/sample/publisher/App.kt
buzzbooster-flutter/lib/main.dart
buzzbooster-ios/BSTSample/AppDelegate.swift
buzzbooster-react-native/App.js
buzzbooster-react-native/Page/HomePage.js

AppKey와 UserID 변경이 필요하다는 것을 Readme뿐만아니라 코드에도 주석으로 추가합니다

[BuzzBooster][MINOR] Add comment for AppKey and User ID

---

buzzad-benefit-extpoint/build.gradle
buzzad-benefit-pop/build.gradle
buzzad-benefit-push/build.gradle
buzzad-benefit-web/android/build.gradle
buzzad-benefit/README.md
buzzad-benefit/build.gradle
buzzscreen-extension-migration/build.gradle
buzzscreen/README.md
buzzscreen/build.gradle
buzzvil-sdk-android/app/build.gradle
buzzvil-sdk/README.md

R231110 스프린트 버전 적용
BuzzBenefit
- buzzvil-bom-5.2;
BuzzAd, Buzzscreen
- buzzad-benefit-3.50;
- buzzscreen-4.44;

R231228; buzzvil-bom-5.2; buzzad-benefit-3.50; buzzscreen-4.44; 

---

buzzvil-sdk-ios/Podfile
buzzvil-sdk-ios/Podfile.lock
buzzvil-sdk-ios/README.md

BuzzvilSDK iOS 5.2.0

---

buzzbooster-ios/CHANGELOG.md

[UPDATE] BuzzBooster iOS CHANGELOG.md

---

buzzvil-sdk-ios/README.md

Buzzvilsdk iOS 5.5.3 update readme

---

buzzvil-sdk-ios/Podfile
buzzvil-sdk-ios/Podfile.lock
buzzvil-sdk-ios/README.md

BuzzvilSDK iOS 5.7.0

---

buzzvil-sdk-ios/Podfile
buzzvil-sdk-ios/Podfile.lock
buzzvil-sdk-ios/README.md
buzzvil-sdk-ios/buzzvil-sdk-ios.xcodeproj/project.pbxproj

BuzzvilSDK iOS 5.9.0

---

buzzvil-sdk-ios/Podfile
buzzvil-sdk-ios/Podfile.lock
buzzvil-sdk-ios/README.md

Buzzvil SDK Release 5.9.5 ~ 5.9.7

BuzzvilSDK iOS 5.9.7

---

buzzvil-sdk-ios/Podfile
buzzvil-sdk-ios/Podfile.lock
buzzvil-sdk-ios/README.md
buzzvil-sdk-ios/buzzvil-sdk-ios.xcodeproj/xcshareddata/xcschemes/buzzvil-sdk-ios-objc.xcscheme
buzzvil-sdk-ios/buzzvil-sdk-ios.xcodeproj/xcshareddata/xcschemes/buzzvil-sdk-ios-swift 1.xcscheme
buzzvil-sdk-ios/buzzvil-sdk-ios.xcodeproj/xcshareddata/xcschemes/buzzvil-sdk-ios-swift.xcscheme

Buzzvil SDK Release 5.11.2 ~ 5.11.4

BuzzvilSDK iOS 5.11.4

---

buzzvil-sdk-android/app/src/main/java/com/buzzvil/sample/buzzvilsdksample/nativead/NativeCustomActivity.kt
buzzvil-sdk-ios/buzzvil-sdk-ios-objc/Native/Carousel/CarouselCell.m
buzzvil-sdk-ios/buzzvil-sdk-ios-swift/Native/Carousel/CarouselCell.swift

https://github.com/Buzzvil/docs.buzzvil.com/pull/328 와 동일한 내용을 퍼블릭 샘플앱에도 추가합니다.

네이티브 2.0 광고 이벤트 리스너 등록하기에 주의사항을 추가합니다.

---

buzzvil-sdk-android/app/build.gradle

- Android 14 대응 반영
- Pop 기능 사용을 위해서 의존성 추가

Buzzvil SDK 5.13.+

---

buzzvil-sdk-ios/Podfile
buzzvil-sdk-ios/Podfile.lock
buzzvil-sdk-ios/README.md

Buzzvil SDK Release 5.13.0 ~ 5.13.1

BuzzvilSDK iOS 5.13.1

---

buzzvil-sdk-android/app/src/main/java/com/buzzvil/sample/buzzvilsdksample/Constant.kt
buzzvil-sdk-android/app/src/main/java/com/buzzvil/sample/buzzvilsdksample/MainActivity.kt
buzzvil-sdk-android/app/src/main/java/com/buzzvil/sample/buzzvilsdksample/benefithub/BenefitHubFragmentActivity.kt
buzzvil-sdk-android/app/src/main/res/layout/activity_main.xml

5.13.0 배포 후 퍼블릭 샘플앱에서 잘 동작하는지 테스트하였습니다.

Add Pop sample code

---

buzzvil-sdk-ios/Podfile
buzzvil-sdk-ios/Podfile.lock
buzzvil-sdk-ios/README.md
buzzvil-sdk-ios/buzzvil-sdk-ios-objc/Banner/BannerViewController.h
buzzvil-sdk-ios/buzzvil-sdk-ios-objc/Banner/BannerViewController.m
buzzvil-sdk-ios/buzzvil-sdk-ios-objc/Feed/Custom/CustomFeedHeaderView.m
buzzvil-sdk-ios/buzzvil-sdk-ios-objc/ViewController.m
buzzvil-sdk-ios/buzzvil-sdk-ios-swift/Banner/BannerViewController.swift
buzzvil-sdk-ios/buzzvil-sdk-ios-swift/ViewController.swift
buzzvil-sdk-ios/buzzvil-sdk-ios.xcodeproj/project.pbxproj

Buzzvil SDK Release 5.15.0 ~ 5.15.2

BuzzvilSDK iOS 5.15.2

---

buzzvil-sdk-android/app/build.gradle
buzzvil-sdk-android/app/src/main/java/com/buzzvil/sample/buzzvilsdksample/nativead/NativeCarouselActivity.kt
buzzvil-sdk-android/app/src/main/java/com/buzzvil/sample/buzzvilsdksample/nativead/NativeCustomActivity.kt
buzzvil-sdk-android/app/src/main/java/com/buzzvil/sample/buzzvilsdksample/nativead/NativeSimpleActivity.kt
buzzvil-sdk-android/app/src/main/res/layout/activity_native_carousel.xml

https://github.com/Buzzvil/docs.buzzvil.com/pull/347 연계 작업입니다.
가이드 업데이트와 함께 퍼블릭 샘플앱 코드도 업데이트합니다.

[OUTPUT-4045] onResume에서 네이티브 베네핏허브 진입점의 리워드를 업데이트 합니다.

---

buzzbooster-ios/Podfile
buzzbooster-ios/Podfile.lock
buzzvil-sdk-ios/Podfile
buzzvil-sdk-ios/Podfile.lock
buzzvil-sdk-ios/README.md
buzzvil-sdk-ios/buzzvil-sdk-ios-objc/AppDelegate.m
buzzvil-sdk-ios/buzzvil-sdk-ios-swift/AppDelegate.swift

Buzzvil SDK Release 5.17.0 ~ 5.17.4

BuzzvilSDK iOS 5.17.4

---

buzzvil-sdk-ios/Podfile
buzzvil-sdk-ios/Podfile.lock
buzzvil-sdk-ios/buzzvil-sdk-ios-objc/AppDelegate.m
buzzvil-sdk-ios/buzzvil-sdk-ios-swift/AppDelegate.swift

buzzvilsdk-ios 5.23.x
- MissionPack 기능 추가
- MissionPack 관련 커스터마이징 코드 추가

buzzvilsdk-ios 5.23.x

---

buzzvil-sdk-ios/Podfile
buzzvil-sdk-ios/Podfile.lock

Sample App 의 SDK 버전을 업데이트 합니다.

[BuzzvilSDK iOS 5.27.1] version update

---

buzzvil-sdk-ios/Podfile
buzzvil-sdk-ios/Podfile.lock
buzzvil-sdk-ios/buzzvil-sdk-ios.xcodeproj/project.pbxproj

iOS BuzzvilSDK Version Update to 5.29.2

BuzzvilSDK iOS 5.29.x

---

buzzvil-sdk-ios/Podfile
buzzvil-sdk-ios/Podfile.lock

BuzzvilSDK iOS 5.31.x

---

open_source_license.md

Android, iOS 오픈소스 라이센스 파일 (/open_source_license.md) 을 buzzvilSdkSamples 리포에 추가합니다.

[CL-235] Add open_source_license.md

---

buzzvil-sdk-v5-ios/Podfile
buzzvil-sdk-v5-ios/Podfile.lock
buzzvil-sdk-v6-ios/Podfile
buzzvil-sdk-v6-ios/Podfile.lock
buzzvil-sdk-v6-ios/buzzvil-sdk-ios-objc/BenefitHub/BenefitHubViewController.m
buzzvil-sdk-v6-ios/buzzvil-sdk-ios-swift/BenefitHub/BenefitHubViewController.swift
buzzvil-sdk-v6-ios/buzzvil-sdk-ios-swiftui/BenefitHub/BenefitHubView.swift
buzzvil-sdk-v6-ios/buzzvil-sdk-ios-v6.xcodeproj/project.pbxproj

샘플앱의 SDK 버전을 업데이트 하고, 변경된 인터페이스를 적용 합니다.

[SDK Version Update] BuzzvilSDK iOS v6.1.0 / v5.35.0

---

buzzvil-sdk-v6-ios/buzzvil-sdk-ios-objc/BenefitHub/BenefitHubNavigationCustomContainerViewController.h
buzzvil-sdk-v6-ios/buzzvil-sdk-ios-objc/BenefitHub/BenefitHubNavigationCustomContainerViewController.m
buzzvil-sdk-v6-ios/buzzvil-sdk-ios-objc/ViewController.m
buzzvil-sdk-v6-ios/buzzvil-sdk-ios-swift/BenefitHub/BenefitHubNavigationCustomContainerViewController.swift
buzzvil-sdk-v6-ios/buzzvil-sdk-ios-swift/ViewController.swift
buzzvil-sdk-v6-ios/buzzvil-sdk-ios-v6.xcodeproj/project.pbxproj

reviewer: @ssmmkk00 
Navigation Custom 사용시 활용해야 하는 코드를 추가 했습니다.

iOS 의 NavigationBar 커스텀에 대한 내용을 업데이트 합니다.

---

buzzvil-sdk-v6-android/.gitignore
buzzvil-sdk-v6-android/app/build.gradle.kts
buzzvil-sdk-v6-android/app/src/main/java/com/buzzvil/sample/buzzvil_sdk_v6_sample/App.kt
buzzvil-sdk-v6-android/app/src/main/java/com/buzzvil/sample/buzzvil_sdk_v6_sample/MainActivity.kt

Buzzvil SDK Android v6.1.1

---

buzzvil-sdk-v6-ios/Podfile
buzzvil-sdk-v6-ios/Podfile.lock
buzzvil-sdk-v6-ios/buzzvil-sdk-ios-objc/EntryPoint/EntryPointViewController.h
buzzvil-sdk-v6-ios/buzzvil-sdk-ios-objc/EntryPoint/EntryPointViewController.m
buzzvil-sdk-v6-ios/buzzvil-sdk-ios-objc/ViewController.m
buzzvil-sdk-v6-ios/buzzvil-sdk-ios-swift/EntryPoint/EntryPointViewController.swift
buzzvil-sdk-v6-ios/buzzvil-sdk-ios-swift/ViewController.swift
buzzvil-sdk-v6-ios/buzzvil-sdk-ios-swiftui/ContentView.swift
buzzvil-sdk-v6-ios/buzzvil-sdk-ios-swiftui/EntryPoint/EntryPointView.swift
buzzvil-sdk-v6-ios/buzzvil-sdk-ios-v6.xcodeproj/project.pbxproj

BuzzvilSDK iOS 6.2.x
